language: node_js

node_js:
  - node

after_success: npm run coverage

stages:
  - name: Test
    if: type != cron
  - name: Release
    if: type != cron AND branch = master AND commit_message !~ /(release|no-release)/
  - name: Update
    if: branch = master AND type = cron

jobs:
  include:
    - stage: Update
      install: npm install --no-package-lock
      before_script:
        - git config user.email ${GITHUB_EMAIL:-"travis@travis-ci.org"}
        - git config user.name ${GITHUB_USER:-"Travis CI"}
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout master
      script: npm run cronjob
    - stage: Release
      node_js: lts/*
      install: npm install --no-package-lock
      before_script:
        - git config user.email ${GITHUB_EMAIL:-"travis@travis-ci.org"}
        - git config user.name ${GITHUB_USER:-"Travis CI"}
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout master
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release
        on:
          branch: master
