#!/usr/bin/env node

'use strict'

const parseDecimalNumber = require('parse-decimal-number')
const { includes, camelCase, reduce } = require('lodash')
const writeJsonFile = require('write-json-file')

const papa = require('papaparse')
const got = require('got')

// https://www.papaparse.com/docs#config
const PARSER_OPTS = {
  header: true,
  trimHeaders: true,
  dynamicTyping: true,
  skipEmptyLines: true
}

const toMap = obj =>
  reduce(
    obj,
    (acc, value, name) => {
      const key = camelCase(name)
      return {
        ...acc,
        [key]: includes(value, ',') ? parseDecimalNumber(value) : value
      }
    },
    {}
  )

;(async () => {
  const { body } = await got(
    'https://moz.com/top-500/download/?table=top500Domains'
  )
  const { data } = papa.parse(body, PARSER_OPTS)
  const buffer = reduce(data, (acc, obj) => [...acc, toMap(obj)], [])

  await writeJsonFile('top-sites.json', buffer)
})()
