#!/usr/bin/env node

'use strict'

const { orderBy, includes, camelCase, reduce } = require('lodash')
const parseDecimalNumber = require('parse-decimal-number')
const writeJsonFile = require('write-json-file')
const PCancelable = require('p-cancelable')
const cheerio = require('cheerio')
const papa = require('papaparse')
const pAny = require('p-any')
const got = require('got')

// https://www.papaparse.com/docs#config
const PARSER_OPTS = {
  header: true,
  trimHeaders: true,
  dynamicTyping: true,
  skipEmptyLines: true
}

const toMap = obj =>
  reduce(
    obj,
    (acc, value, name) => {
      const key = camelCase(name)
      return {
        ...acc,
        [key]: includes(value, ',') ? parseDecimalNumber(value) : value
      }
    },
    {}
  )

const fromCSV = PCancelable.fn(async onCancel => {
  const req = got('https://moz.com/top-500/download/?table=top500Domains')
  onCancel(() => req.cancel())
  const { body } = await req
  const { data } = papa.parse(body, PARSER_OPTS)
  const items = reduce(data, (acc, obj) => [...acc, toMap(obj)], [])
  return orderBy(items, ['linkingRootDomains'], ['desc', 'desc']).map((item, index) => {
    item.rank = index + 1
    return item
  })
})

const fromURL = PCancelable.fn(async onCancel => {
  const req = got('https://moz.com/top500')
  onCancel(() => req.cancel())

  const { body } = await req
  const $ = cheerio.load(body)

  const el = $('tbody tr')
    .map((_, element) => {
      const selector = $(element)
      return {
        rank: Number(selector.find('td:nth-child(1)').text()),
        rootDomain: selector.find('td:nth-child(2)').text().replaceAll('\n', '').trim(),
        linkingRootDomains: parseDecimalNumber(selector.find('td:nth-child(3)').text()),
        domainAuthority: Number(selector.find('td:nth-child(4)').text())
      }
    })
    .get()

  return el
})

const main = async () => {
  const data = await pAny([fromURL(), fromCSV()])
  await writeJsonFile('top-sites.json', data)
}

main().catch(error => console.error(error) || process.exit(1))
